### PR TITLE
Feature/filtering/firebase and search consultant UI

### PR DESCRIPTION
**Pull request by drkchn**
# High Level Summary of the PR
- Backend business logic: NoSQL queries to the Firestore database
- Integrated the filtering parameters into the query: consultant's specialty, consultant's years of experience, and consultant's geographic region
- Searching function occurs server-side
- One filtering function occurs client-side, and the second filtering function occurs server-side
- Parameter typings match the Notion Database Schema page
- Incorporated unit testing with Jest
- This PR is a 'cousin' of Miguel's PR #11
- I have been pulling Miguel's branch and merging commits to decrease the potential for merge conflicts

# What the User can do
1. User can search consultants by `name`
2. User can filter consultants by the following: `(specialty1 OR specialty2 OR ...) AND experienceYears >= minYearsOfExperience AND (region1 OR region2 OR ...)`
2a. This is performed client-side due to limitations of Firestore NoSQL queries
2b. Firestore queries can only have one instance of `(X OR Y OR Z)` when querying the database
3. User can filter consultants by the following: `(specialty1) AND (experienceYears >= minYearsOfExperience) AND (region1 OR region2 OR ...)`
3a. This is performed server-side

Note: experienceYears is a number type in the Firestore (Notion Database Schema page), and the user will provide the minYearsOfExperience argument

# All files altered
`service.js`, `service.test.js`, `../firebase/config.js`, `jest.config.js`, `babel.config.js`, `.gitignore`, `.firebase.json`, `.firebaserc`

# Significant files altered
## service.js
- Contains the NoSQL queries for searching and filtering consultants
- User can search consultants by full name (server-side)
- User can filter consultants using bullet 2 (client-side) and bullet 3 (server-side) as noted above

## service.test.js
- Unit testing through Jest
- Firestore functions were mocked in Jest

# Other files altered
## ../firebase/config.js
- Minor alterations regarding the import statements for Jest compatibility

## jest.config.js
- Configurations for Jest. Added statements for Jest to be ES6 syntax-compatible

## babel.config.js
- Added statements for Jest compatibility. Previous statements/code remain untouched

## .gitignore
- Added `/coverage` directory from Jest. Added `.log` files

## .firebase.json and .firebaserc
- Attempted to unit test code through Firebase CLI and attempted to connect with a Firestore emulator, but did not succeed

### CODE REVIEW

**Comment by MikeProduce** [comment]
Hey @drkchn I noticed you passed in the maxPrice parameter but I do not see it being used in the filterConsultantClientSide. I am missing something by any chance here?

**Comment by drkchn** [comment]
Hey @MikeProduce Good observation and question, I omitted the maxPrice filtering because the Database Schema makes it tricky to implement the filtering by price. The price for the consultants is under the `services` field, which is an array of hashmaps with the `price` as one of the keys in the hashmap.

For the filterConsultantsClientSide, I could request the `services` field and find the `price`, but this would introduce excess work since we don't necessarily need the entire `services` array. I looked into other ways to make this process easier, and one way is we could add a maxPrice and minPrice fields into the database or add a prices array field. We would have a field that decouples the prices from the services field.

Decoupling the price from the services field (by adding more fields to the database) would allow us to filter server-side as well since we aren't able to query the database for the price right now.

**Comment by drkchn** [comment]
Thanks @MikeProduce, for the meeting yesterday. Here's a summary of the items we discussed:

- Denormalize the `prices` in the Firestore database (either by adding a separate maxPrice, minPrice, or prices array field TBD)
- I'll think more about what would be the best approach for denormalization
- Server-side filtering is better than client-side since that's the purpose of having a Firestore database
- Therefore, users should only be able to choose one specialty only (Currently, users can choose multiple specialties)
- In the Notion Database Schema page, changed specialty wording to `expertise` (based on Miguel's meeting with Paul)

Please feel free to let me know if I've missed anything else, thanks!

**Comment by drkchn** [comment]
# Updates
- Filtering operation is as follows: `(expertise == inputExpertise) AND (experienceYears >= inputMinYearsOfExperience) AND (inputRegion1 OR inputRegion2 OR ...) AND (inputMinPrice == 0) AND (maxPrice <= inputMaxPrice)`
- Added two new fields: minPrice and maxPrice to filter consultants by price server-side
- minPrice field will be used to filter for pro-bono consultants
- maxPrice is necessary because we are denormalizing the database schema

**Review by MikeProduce — APPROVED** [review]
nice!

**Pull request merged**
