### PR TITLE
Origin/feature/profile/creation

### PR DESCRIPTION
**Pull request by ialoko**
In this PR,

I integrated the Social Entrepreneur profile creation feature with the Consultant profile creation feature.

## Create a new account
- Create a new account: A Consultant or Social Entrepreneur
-  After creating a new account, a new user is directed to the login page to complete their profile (in the future, they will be required to verify their email before they can login).
- Consultants need to be manually approved before they can login and complete their profile

## Profile Creation

-  A user should be able to join an enterprise (the browse enterprise feature is incomplete right now but a user can create a new enterprise)
-  Complete their profile information depending on if they are an entrepreneur or a consultant
- Once a user has completed their profile, they are directed to the dashboard and their information is updated in the database in the Entrepreneur collection or the Consultant collection.

Here is a collection of a few of the screens. Let me know if there are any questions

IMG_3313
IMG_3314
IMG_3330
IMG_3331
IMG_3333
IMG_3334

### CODE REVIEW

**Review by MikeProduce — COMMENTED** [review]
Screenshot 2024-01-21 205106
Hey are you familiar with this package apparently it only works on mac os. Which is not letting me run the code on my machine

**Comment by MikeProduce** [comment]
sorry wrong image 
error

**Comment by ialoko** [comment]
@MikeProduce 

Yeah. Honestly, basically I started getting an error when I tried to run my code after pulling from main last week. And I researched the error and it mentioned needing to update fsevents on Mac and it fixed my issue. Does it the code run for you if you just uninstall it?

If it runs for you when you uninstall it then I could probably just uninstall it and commit the package.json without it

**Comment by MikeProduce** [comment]
yea youre right thanks. good solution, I hope no one really needed it i will bring it up in the meeting to see if anyone was using it

**Comment by quanphan2906** [comment]
I have four comments:
- For the social entrepreneur, on the Enterprise creation step, the UI on iOS is a tad bit weird. The entire screen takes only half of the view height of my phone despite having more fields as you scroll down!: Weird screen
- What is the steps to "manually approve" a consultant? Is this the finalized flow for this batch or do you intend to implement a different flow soon?
- I cannot manually verify the fact that when a user signs up, their data is in the database. (Unless we somehow make this easier, at this point of the project, I will blindly trust that this is implemented correctly).
- I don't know how to manually approve a consultant yet, so I cannot test the profile creation flow for the consultant, and check whether they appear on the list of consultant in the app. If you can show me how you are currently approving a consultant, I can do manual testing for ya.

**Comment by ialoko** [comment]
@quanphan2906 

Hey! Yeah I’m planning on fixing up the UI this week in a separate PR since honestly UI takes me a bit more time. 

Also don’t worry. I actually checked through the database to verify new users were being stored in the database properly. 

For manually approving a new Consultant, I talked with Paul to create a method he was comfortable with. But basically it just needs to be manually approved in the database itself. You have to filter the users collection on the field isApproved and change the Boolean to true.

**Comment by quanphan2906** [comment]
I followed your instruction and managed to approve the consultant. As long as you and Paul have agreed on a particular flow to approve the consultant, that would be good.

I do notice that the consultant also have to choose/create an entreprise through which they belong to. Is this intentional?

Also, there are some conflicts with the dev branch. If you can resolve the conflicts, I'd be happy to approve the PR.

Thank you for the hard work @ialoko @dilpreetksamra

**Comment by ialoko** [comment]
@quanphan2906 So I just pulled from dev to try to resolve the merge conflicts but now I'm getting an non-std C++ exception. I remember Eunice saying she was getting this error from main in the last meeting. And I also tried following Derek's steps in PR #33 but it didn't seem to solve the issue. Can you try testing it on your end to see if you're getting the error.

**Comment by quanphan2906** [comment]
@ialoko I'm not getting that error. I am serving the app from my Windows 11 machine, and opening the app through Expo Go on iOS 16

**Comment by ialoko** [comment]
@quanphan2906 

yeah that’s so weird that you’re not getting the error. I did resolve the merge conflicts with dev but since I can’t fix that error on my computer, I can’t test the app anymore. 

I also can’t tell if it makes sense to merge this PR if it’s working for you and not working for me.

**Pull request closed without merging**
