### PR TITLE
Install es-lint prettier.configs

### PR DESCRIPTION
**Pull request by MikeProduce**
I changed 'useTabs: true'. @quanphan2906  If you want to modify anything else, please let me know before we make the final push so I can resubmit. I don't mind going with your settings, as I have no preferences as long as everything is consistent. If anyone else would like to chime in, that would be great.

### CODE REVIEW

**Comment by MikeProduce** [comment]
Also in the future i will use the feature/branch-name convention. when creating branches sorry about that

**Comment by quanphan2906** [comment]
@MikeProduce Let's go with `semi: true` so that it puts semi-colon at the end of the line (just good practice). I prefer `tabWidth: 4` if that doesn't bother anyone

**Comment by MikeProduce** [comment]
@quanphan2906 done ! :D let me know if anyone needs anything else guys.

**Review by quanphan2906 — APPROVED** [review]
All look good to me!

**Pull request merged**
