### PR TITLE
Meeting dashboard and schedule settings screen

### PR DESCRIPTION
**Pull request by quanphan2906**
In this PR, I implement the UI of the meeting dashboard and the scheduling settings screen.

# Meeting dashboard

Entry point: `MeetingDashboard.js`

Note that none of the buttons are doing anything right now. In the future, the `Join` button will lead the users directly to the meeting on Zoom/Google Meet/on our platform and `Schedule New Meeting` will lead users to the `SearchConsultant` page.

image

# Scheduling settings screen

Entry point: `EditAvailability.js`

For now, when users change the values in this screen and hit `Save`, the value will persist in the app until the app is reloaded. In the future, when users change the values in this screen and hit `Save`, the database will be updated, and the changes will persist through reloads.

image

image

image

### CODE REVIEW

**Comment by MikeProduce** [comment]
Pretty cool functionality you have there @quanphan2906. 

I pulled it into my machine and the only thing I noticed was that MeetingDashboard is misspelled. I believe you have MeetinDashboard in the component.

I could personally follow the logic here. Im not sure if you would want Ralph to look at it but other than the typo im ok with pushing it to Dev but before that i just have a couple of things.

1.I noticed you also pushed to main, Did you mean to push to dev? 

2.I did see your message with the about the big pr. Is this all of it or did you still have more on top of this ? 

3.Also before we merge, do you mind pulling from dev fixing the merge conflicts and then pushing again? I did this and got a couple of conflicts in the index.js file and some of the styling. Let me know if you have any questions! :D

**Review by MikeProduce — COMMENTED** [review]
@quanphan2906

**Comment by quanphan2906** [comment]
@MikeProduce Thanks for your review! To your questions:

1. Yes, I should have merged into `dev` instead of `main`. Great catch! Already changed the base branch into `dev`.
2. Yes, this is the entire PR
3. Just resolved the conflicts. All good to be merged!

**Review by MikeProduce — APPROVED** [review]
great job @quanphan2906 !

**Pull request merged**
