### PR TITLE
Feature/payment

### PR DESCRIPTION
**Pull request by rayyanahmed021**
I created a payment form that would allow users to enter the credit card information to complete the transaction.

### CODE REVIEW

**Comment by MikeProduce** [comment]
Hey @rayyanahmed021 I noticed you are trying to merge to main. Do you mind trying to merge to dev first ? :D

**Comment by rayyanahmed021** [comment]
> Hey @rayyanahmed021 I noticed you are trying to merge to main. Do you mind trying to merge to dev first ? :D

oh, my bad. I just changed it. You can tell its my first PR 😅.

**Comment by MikeProduce** [comment]
no worries there is just a few conflicts as well, do you mind looking over these? 

the way to check is that you would

1. git pull origin dev in to local feature/payment branch
2. fix the merge conflicts 
3. try to push again into dev and the conflicts should be resolved :D

**Review by MikeProduce — APPROVED** [review]
LGTM

**Pull request merged**
