### PR TITLE
Debugging Expo Go build: non-std C++ exception

### PR DESCRIPTION
**Pull request by drkchn**
# Changes
- Commits to various files to diagnose the error after building the application in Expo Go
- Resolved a `non-std C++ exception` error when building the mobile application on Expo Go
- _Now_: Expo Go build works on this branch & functions normally
- Tested locally on my iOS device (iPhone) through the native Expo Go iOS app
- Tested locally using the web browser (`port: 8081`)

# Before running the Expo Go build
- Delete the `package-lock.json` file and the `node_modules` directory
- Run `npm install` so everything is fresh

I also ran the following two commands below in my terminal:
- `lsof -t -i :8081 | xargs kill`
- `npm run --reset-cache`
- This is based on the following [StackOverflow answer](https://stackoverflow.com/questions/76375461/how-can-i-solve-a-non-std-c-exception-in-my-react-native-typescript-applicatio) for resolving a `non-std C++ exception` error.

# Working Expo Go build
Left image (Calendar) is the landing screen when you run the Expo Go build. Right image (Home page) is when you click on the home button at the bottom of the screen.

### CODE REVIEW

**Comment by drkchn** [comment]
Hey @euniceyoh Hopefully the Expo Go build works on your end, let me know, thanks!

**Comment by euniceyoh** [comment]
hey @drkchn i checked out your branch & ran it locally. altho it ran on expo go, i received a console warning & "uncaught error" logs. 
it also looks like the "home" tab for me is missing.  
i haven't looked into these logs yet, but just wanted to update my current status. 

also, could you try creating a completely new git clone of your branch, and testing it out? i tried the same, and on my end, i still faced the non-std C++ exception error (double checked i was on your branch and not main).

<p float="left">
  
  
  
</p>

**Comment by euniceyoh** [comment]
also @drkchn, could you try creating a completely new git clone of your branch, and testing it out? i tried the same, and on my end, i still faced the non-std C++ exception error (double checked i was on your branch and not main).

**Comment by drkchn** [comment]
That's very interesting, @euniceyoh

I'm unsure why the `non-std C++ exception` error persists. I no longer see that error, even when creating a new directory to `git clone` my branch.

I created a brand new, independent directory on my Mac and `git cloned` the `derek-expo-debug-main-branch` only by running the following command: `git clone --single-branch --branch derek-expo-debug-main-branch https://github.com/DFG-SAPSE/SEMS.git`

Then, I took the following steps:
1. Deleted the existing `package-lock.json` file (there was no `node-modules` directory because I'm in the newly created directory)
2. Ran `npm install`
3. Created a `.env` file at the top-most level in my directory (ie. `newlyCreatedDirectory/.env`)
4. Populated my `.env` file with the Firebase credentials (`API_KEY` and `AUTH_DOMAIN`)
5. Ran `npm run start`
6. Once the Expo Go build was finished, I opened the mobile application deployment using my iPhone
7. Everything was operating normally, and I saw the same two photos from my initial comment above

# Try the following
The `.env` file is likely the only difference between our two builds. If the `.env` file is indeed correct, then I'm not sure why your Expo Go build gives you an error. I recommend updating the file, and hopefully, that error will disappear

**Comment by drkchn** [comment]
When I ran `git clone --single-branch --branch derek-expo-debug-main-branch https://github.com/DFG-SAPSE/SEMS.git` to clone my branch, I did get the following warning from `git` about two files with the same name (see below)

I was still able to successfully run my Expo Go build though, so I don't think this warning from `git` is relevant to the `non-std C++ exception` error
```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'app/(booking)/Payment.js'
  'app/(booking)/payment.js'
```

**Comment by euniceyoh** [comment]
hey @drkchn i tried out your branch and it worked for me! i didn't include the .env file last time, which prob was the main issue. thanks for working on this!

**Review by euniceyoh — APPROVED** [review]
exception resolved on my end

**Comment by drkchn** [comment]
Ok great to hear it's working for you! @euniceyoh 

@ialoko I [noticed](https://github.com/DFG-SAPSE/SEMS/pull/32#issuecomment-1928792712) you're getting the `non-std C++ exception` error on the `dev` branch. Do you still get that error when you checkout this branch?

For merging PRs, I think it might be best for this PR #33 to be merged into `dev` before #32, then once you pull the updated `dev` to update your feature branch, your #32 PR should be OK to merge into `dev`

I still need to update this PR because there are some merge conflicts, but I'll plan to merge this PR into `dev` once @ialoko takes a look

**Comment by drkchn** [comment]
# Update - Expo Go OK
After resolving my merge conflicts, I see the login screen when I launch the mobile app in Expo Go

**Comment by drkchn** [comment]
Hey @dilpreetksamra When you pull down my branch and run it, let me know what status you get, thanks!

I'll plan to merge this PR into `dev` once @dilpreetksamra confirms it's working for her, based on today's general meeting. @euniceyoh

**Comment by ialoko** [comment]
@drkchn 
Hey, sorry it took so long to get back to this. I cloned this branch specifically and tested it and it worked for me. I know Dilpreet tested the profile creation branch and got the error so I think after you merge this to main, I will just have to revert the profile creation branch to before I pulled from main and then pull the changes from this branch instead.

**Review by ialoko — APPROVED** [review]
I'm approving this since it worked for me

**Comment by drkchn** [comment]
No worries, great to hear it works for you! @ialoko 

I'll go ahead and merge this PR into `dev` since 2+ people have confirmed it works for them

**Pull request merged**
